<?php

namespace FluxEco\UnibeOmnitrackerClient\Types\UnibeOmnitrackerSoapApi;

use FluxEcoType\FluxEcoAttributeDefinition;

final readonly class BaseDataItemAttributesDefinition
{
    private function __construct(
        public FluxEcoAttributeDefinition $ahv,
        public FluxEcoAttributeDefinition $anrede,
        public FluxEcoAttributeDefinition $anredeuniqueid,
        public FluxEcoAttributeDefinition $countrycode,
        public FluxEcoAttributeDefinition $elternadresszusatz,
        public FluxEcoAttributeDefinition $elternanrede,
        public FluxEcoAttributeDefinition $elternanredeuniqueid,
        public FluxEcoAttributeDefinition $elternlanduniqueid,
        public FluxEcoAttributeDefinition $elternnachname,
        public FluxEcoAttributeDefinition $elternort,
        public FluxEcoAttributeDefinition $elternortuniqueid,
        public FluxEcoAttributeDefinition $elternplz,
        public FluxEcoAttributeDefinition $elternpostfach,
        public FluxEcoAttributeDefinition $elternpostfachvorhanden,
        public FluxEcoAttributeDefinition $elternstrasse,
        public FluxEcoAttributeDefinition $elternvorname,
        public FluxEcoAttributeDefinition $emailprivat,
        public FluxEcoAttributeDefinition $geburtstag,
        public FluxEcoAttributeDefinition $generalnotes,
        public FluxEcoAttributeDefinition $heimatortuniqueid,
        public FluxEcoAttributeDefinition $identifikationsnummer,
        public FluxEcoAttributeDefinition $korrespondenzspraccheuniqueid,
        public FluxEcoAttributeDefinition $land,
        public FluxEcoAttributeDefinition $landuniqueid,
        public FluxEcoAttributeDefinition $lastcompletedcontroller,
        public FluxEcoAttributeDefinition $martikelnmmer,
        public FluxEcoAttributeDefinition $mobilitaetheimuniuniqueid,
        public FluxEcoAttributeDefinition $mutterspracheuniqueid,
        public FluxEcoAttributeDefinition $nachname,
        public FluxEcoAttributeDefinition $nationalitaetuniqueid,
        public FluxEcoAttributeDefinition $parallelstudium,
        public FluxEcoAttributeDefinition $posteltern,
        public FluxEcoAttributeDefinition $poststudierend,
        public FluxEcoAttributeDefinition $pruefingsmisserfolgmajor,
        public FluxEcoAttributeDefinition $qualificationstudiesatuniversityofbern,
        public FluxEcoAttributeDefinition $rechnungeltern,
        public FluxEcoAttributeDefinition $rechnungstudierend,
        public FluxEcoAttributeDefinition $registrationcompleted,
        public FluxEcoAttributeDefinition $semesteruniqueid,
        public FluxEcoAttributeDefinition $studentadresszusatz,
        public FluxEcoAttributeDefinition $studentort,
        public FluxEcoAttributeDefinition $studentortuniqueid,
        public FluxEcoAttributeDefinition $studentplz,
        public FluxEcoAttributeDefinition $studentpostfach,
        public FluxEcoAttributeDefinition $studentpostfachvorhanden,
        public FluxEcoAttributeDefinition $studentstrasse,
        public FluxEcoAttributeDefinition $studiengangsversion,
        public FluxEcoAttributeDefinition $studiengangsversionparallel,
        public FluxEcoAttributeDefinition $studiengangsversionparallelreqects,
        public FluxEcoAttributeDefinition $studiengangsversionparalleluniqueid,
        public FluxEcoAttributeDefinition $studiengangsversionreqects,
        public FluxEcoAttributeDefinition $studiengangsversionuniqueid,
        public FluxEcoAttributeDefinition $studienstruktur,
        public FluxEcoAttributeDefinition $studienstrukturparallel,
        public FluxEcoAttributeDefinition $studienstrukturparallelreqects,
        public FluxEcoAttributeDefinition $studienstrukturparalleluniqueid,
        public FluxEcoAttributeDefinition $studienstrukturreqects,
        public FluxEcoAttributeDefinition $studienstrukturuniqueid,
        public FluxEcoAttributeDefinition $studienstufebfs,
        public FluxEcoAttributeDefinition $studienstufeuniqueid,
        public FluxEcoAttributeDefinition $studierendenkategorieuniqueid,
        public FluxEcoAttributeDefinition $telefon,
        public FluxEcoAttributeDefinition $telefontyp,
        public FluxEcoAttributeDefinition $uniqueid,
        public FluxEcoAttributeDefinition $vorbildungmasterabschluss,
        public FluxEcoAttributeDefinition $vorname,
        public FluxEcoAttributeDefinition $vorname2,
        public FluxEcoAttributeDefinition $vorname3,
        public FluxEcoAttributeDefinition $wunscheinstufungssemester,
    )
    {

    }

    public static function new(): self
    {
        return new self(
            FluxEcoAttributeDefinition::new("AHV", "string"),
            FluxEcoAttributeDefinition::new("Anrede", "string"),
            FluxEcoAttributeDefinition::new("AnredeUniqueid", "int"),
            FluxEcoAttributeDefinition::new("CountryCode", "string"),
            FluxEcoAttributeDefinition::new("ElternAdresszusatz", "string"),
            FluxEcoAttributeDefinition::new("ElternAnrede", "string"),
            FluxEcoAttributeDefinition::new("ElternAnredeUniqueId,", "int"),
            FluxEcoAttributeDefinition::new("ElternLandUniqueId", "int"),
            FluxEcoAttributeDefinition::new("ElternNachname", "string"),
            FluxEcoAttributeDefinition::new("ElternOrt", "string"),
            FluxEcoAttributeDefinition::new("ElternOrtUniqueId", "int"),
            FluxEcoAttributeDefinition::new("ElternPLZ", "string"),
            FluxEcoAttributeDefinition::new("ElternPostfach", "string"),
            FluxEcoAttributeDefinition::new("ElternPostfachVorhanden", "bool"),
            FluxEcoAttributeDefinition::new("ElternStrasse", "string"),
            FluxEcoAttributeDefinition::new("ElternVorname", "string"),
            FluxEcoAttributeDefinition::new("EmailPrivat", "string"),
            FluxEcoAttributeDefinition::new("Geburtstag", "string"),
            FluxEcoAttributeDefinition::new("GeneralNotes", "string"),
            FluxEcoAttributeDefinition::new("HeimatortUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Identifikationsnummer", "string"),
            FluxEcoAttributeDefinition::new("KorrespondenzspraccheUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Land", "string"),
            FluxEcoAttributeDefinition::new("LandUniqueId", "int"),
            FluxEcoAttributeDefinition::new("LastCompletedController", "string"),
            FluxEcoAttributeDefinition::new("Martikelnmmer", "string"),
            FluxEcoAttributeDefinition::new("MobilitaetHeimuniUniqueId", "int"),
            FluxEcoAttributeDefinition::new("MutterspracheUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Nachname", "string"),
            FluxEcoAttributeDefinition::new("NationalitaetUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Parallelstudium", "string"),
            FluxEcoAttributeDefinition::new("PostEltern", "string"),
            FluxEcoAttributeDefinition::new("PostStudierend", "string"),
            FluxEcoAttributeDefinition::new("PruefingsmisserfolgMajor", "string"),
            FluxEcoAttributeDefinition::new("QualificationStudiesAtUniversityOfBern", "string"),
            FluxEcoAttributeDefinition::new("RechnungEltern", "string"),
            FluxEcoAttributeDefinition::new("RechnungStudierend", "string"),
            FluxEcoAttributeDefinition::new("RegistrationCompleted", "string"),
            FluxEcoAttributeDefinition::new("SemesterUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudentAdresszusatz", "string"),
            FluxEcoAttributeDefinition::new("StudentOrt", "string"),
            FluxEcoAttributeDefinition::new("StudentOrtUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudentPLZ", "string"),
            FluxEcoAttributeDefinition::new("StudentPostfach", "string"),
            FluxEcoAttributeDefinition::new("StudentPostfachVorhanden", "string"),
            FluxEcoAttributeDefinition::new("StudentStrasse", "string"),
            FluxEcoAttributeDefinition::new("Studiengangsversion", "string"),
            FluxEcoAttributeDefinition::new("StudiengangsversionParallel", "string"),
            FluxEcoAttributeDefinition::new("StudiengangsversionParallelReqEcts", "string"),
            FluxEcoAttributeDefinition::new("StudiengangsversionParallelUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudiengangsversionReqEcts", "string"),
            FluxEcoAttributeDefinition::new("StudiengangsversionUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Studienstruktur", "string"),
            FluxEcoAttributeDefinition::new("StudienstrukturParallel", "string"),
            FluxEcoAttributeDefinition::new("StudienstrukturParallelReqEcts", "string"),
            FluxEcoAttributeDefinition::new("StudienstrukturParallelUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudienstrukturParallelUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudienstrukturUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudienstufeBFS", "string"),
            FluxEcoAttributeDefinition::new("StudienstufeUniqueId", "int"),
            FluxEcoAttributeDefinition::new("StudierendenkategorieUniqueId", "int"),
            FluxEcoAttributeDefinition::new("Telefon", "string"),
            FluxEcoAttributeDefinition::new("TelefonTyp", "string"),
            FluxEcoAttributeDefinition::new("UniqueId", "int"),
            FluxEcoAttributeDefinition::new("VorbildungMasterabschluss", "string"),
            FluxEcoAttributeDefinition::new("Vorname", "string"),
            FluxEcoAttributeDefinition::new("Vorname2", "string"),
            FluxEcoAttributeDefinition::new("Vorname3", "string"),
            FluxEcoAttributeDefinition::new("WunschEinstufungsSemester", "string"),
        );
    }
}